[package]
name = "aos_packet_derive"
version = "0.1.0"
authors = ["Gaunsessa <0167623@schoolsnet.act.edu.au>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.38"
proc-macro2 = "1.0"
quote = "1.0"